### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by dgcovell** [velkoborsky/scaffvis#1]
Having trouble with installation. Followed procedures (download jchem zip and copied required files to scaff-vis folder. Don't appear to find an installation file. Build.sbt looks promising, but not for a windows installation. Please point me to relevant documents/steps.

Thanks,
David

**Comment by velkoborsky** [comment]
Hi David,

With Build.sbt you are definitely on the right track. It is a build file
for the SBT build system. You need to install the SBT first (and add it to
the path).

You can try to approximately follow the server installation guide:

https://github.com/velkoborsky/scaffvis/blob/master/doc/server-installation.md

Scaffvis works fine on both Windows and Linux and the way to run it is
almost the same on both. If you get stuck, feel free to post the error
messages here.

Best,

Jakub
